### ISSUE TITLE
Can't merge!

### ISSUE THREAD

**Issue by alcala21** [githubteacher/welcome-june#127]
I got the message:

Merge attempt failed
Base branch was modified. Review and try the merge again.

**Comment by loranallensmith** [comment]
Hi @alcala21!  It looks like this got merged in #113.  Is that right?

**Comment by alcala21** [comment]
Yes, somehow I was later able to merge.

**Comment by scordle** [comment]
I had the same problem, but the merge worked OK the second time.

**Comment by loranallensmith** [comment]
Glad to hear everything merged in.  :+1:
