### ISSUE TITLE
Can I assign multiple people to a pull request

### ISSUE THREAD

**Issue by courtenayt** [githubteacher/welcome-june#129]
I'd like to be able to use the assign feature to add multiple people for a code review of a pull request. Is this possible? It seems that I can only add one person as an assignee at a time.

**Comment by loranallensmith** [comment]
Hey @courtenayt!  That's a great question.  You can only assign one person to an Issue or Pull Request at one time, but you can always @mention users to pull them into the conversation in case they aren't watching the project or subscribed to a particular thread.

One thing that helps me when I assign someone to an Issue or Pull Request is to think of that person as the person responsible for the next step.  Who is charged with moving this Issue or Pull Request toward resolution?

**Comment by loranallensmith** [comment]
As a project progresses, the primary responsible person may change, and you can reassign the Issue or Pull request to let everyone know.

**Comment by courtenayt** [comment]
Thanks. That is an interesting concept. We tend to consider the person who created the pull request as the responsible party and wanted a more formal way than an @ mention to list all of those requested to do a code review before the merge. I hope that GitHub will consider adding that as a future enhancement. We are currently using a separate tool to manage assigning people to review, setting dates for the review to be completed and reminding users of their review lists and it would be great if we could do more directly within GitHub

**Comment by loranallensmith** [comment]
Your approach makes a lot of sense, @courtenayt. :+1:  I can't speak for the specific roadmap, but I know several teams have integrated GitHub into their project management tool to have that type of control over tasks.  There is a bit more info available about integrations at https://github.com/integrations.

**Comment by courtenayt** [comment]
:+1:

**Comment by rambo-panda** [comment]
+1 
![image](https://cloud.githubusercontent.com/assets/2776050/15177273/c2dd1a54-17a1-11e6-9b0d-abb327bafc67.png)
This is before we used the stash's JIRA

One of my favorites is that it can be set up to 2 people to agree.
