### ISSUE TITLE
Can i define an upstream merge flow between branches ?

### ISSUE THREAD

**Issue by saardemri** [githubteacher/welcome-june#132]
lets say that i want to create 3 branches x , y ,z.
now i want to define that each time someone push to branch x it will automatically creates pull request to branch y and then to z ?
- if the pull request can be automatically merge ill want it to be merge directly .

**Comment by githubteacher** [comment]
Yes, you can set the upstream branch you would like to push to from your local repository. This is something we cover in the GitHub for Developers class!

**Comment by saardemri** [comment]
Ok , ill assign to it .
