### ISSUE TITLE
How can I stop getting emails with the comments from an issue?

### ISSUE THREAD

**Issue by alcala21** [githubteacher/welcome-june#19]
I just noticed that I got a lot of new emails with comments from the issue that I commented on.

**Comment by stoddard1974** [comment]
Yes! I need help with that too!

**Comment by ChuaMichelle** [comment]
Same here

**Comment by loranallensmith** [comment]
There are a few options here.  You can choose to Unwatch the repository in the upper right corner of the repository screen.  You can also be a bit more granular and choose to Unsubscribe from a particular Issue.

**Comment by alcala21** [comment]
Thank you, @loranallensmith!
