### ISSUE TITLE
I registered for this, but I can't join because the session is full ?

### ISSUE THREAD

**Issue by dancarey** [githubteacher/welcome-june#22]
What gives?

**Comment by loranallensmith** [comment]
Apologies for the trouble joining @uberdanzik.  We are troubleshooting an issue with GoToWebinar that is preventing many students from joining.  I will comment back on this issue as we know more!

**Comment by githubteacher** [comment]
@uberdanzik we apologize for the inconvenience. We will definitely schedule another class very soon - after we have sorted out the issue with GoToWebinar!
