### ISSUE TITLE
Can i block collaborators from push to master directly .

### ISSUE THREAD

**Issue by saardemri** [githubteacher/welcome-june#37]
Can i block collaborators from push to master directly but to allow them to push to the branches ?

**Comment by loranallensmith** [comment]
Hi @saardemri!  You don't have the option to assign per-branch permissions, but an alternative workflow is to allow users to Fork your repository to their own account and submit changes back to your repository using Pull Requests.

**Comment by loranallensmith** [comment]
Forking creates an identical copy of your repository at that point in time that is automatically linked back to your project.

**Comment by saardemri** [comment]
Thanks

**Comment by courtenayt** [comment]
@loranallensmith Thanks! I would also like the ability to block users from commiting directly from master without forcing users to use the forking methodology. Is there any plan to add this in the future? It's really helpful on Atlassian Stash to be able to do that.

**Comment by mike-asfaw** [comment]
This request is an important feature for our software development process.

**Comment by loranallensmith** [comment]
@courtenayt and @mike-asfaw while I can't speak to the specific roadmap for features, I know this is one enhancement students in our classes often bring up as a helpful addition to our toolset.  I will make sure to pass word along that this type of feature would be a great help. :+1:

**Comment by courtenayt** [comment]
:+1: Thanks!

**Comment by sorianojerome** [comment]
We really need this. Thanks!
